dependencies:
  - yarn.lock

gh-actions:
  - .github/workflows/**/*

tests:
  - src/tests/**/*

components:
  - src/components/**/*

ts-types:
  - src/types/**/*

documentation:
  - README.md
  - CODE_OF_CONDUCT.md
