name: Deploy production
on:
  workflow_dispatch:
  release:
    types:
      - created
      - published
      - edited
      - released

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        run: yarn install && yarn deploy
